import { Precedent } from "@/types/database";

export const PRECEDENTS_DB: Omit<Precedent, "id" | "created_at" | "relevance_score">[] = [
  // İŞ HUKUKU
  {
    court: "Yargıtay 9. Hukuk Dairesi",
    case_number: "2023/1245 E., 2023/5678 K.",
    date: "2023-03-15",
    category: "is_hukuku",
    summary: "İşçinin haklı nedenle fesih hakkı - Maaşın düzensiz ödenmesi. İşveren, işçinin maaşını üst üste 3 ay geç ödemiş, işçi iş sözleşmesini haklı nedenle feshetmiştir.",
    ruling: "İşçinin haklı nedenle fesih hakkı bulunduğuna, kıdem tazminatı ve diğer alacaklarının ödenmesine karar verilmiştir.",
    keywords: ["maaş gecikmesi", "haklı fesih", "kıdem tazminatı", "iş sözleşmesi", "işçi hakları"],
    outcome: "plaintiff_won",
  },
  {
    court: "Yargıtay 9. Hukuk Dairesi",
    case_number: "2022/8901 E., 2023/2345 K.",
    date: "2023-01-20",
    category: "is_hukuku",
    summary: "İşe iade davası - Geçerli neden olmadan fesih. İşveren, performans düşüklüğü iddiasıyla işçiyi çıkarmış ancak performans değerlendirme belgesi sunamamıştır.",
    ruling: "Feshin geçersizliğine ve işçinin işe iadesine karar verilmiştir. İşe başlatmama halinde 8 aylık tazminat öngörülmüştür.",
    keywords: ["işe iade", "geçersiz fesih", "performans", "iş güvencesi", "tazminat"],
    outcome: "plaintiff_won",
  },
  {
    court: "Yargıtay 22. Hukuk Dairesi",
    case_number: "2022/5567 E., 2023/1122 K.",
    date: "2023-02-10",
    category: "is_hukuku",
    summary: "Fazla mesai ücreti talebi - İşçinin günde 11 saat çalıştırılması. Bordrolarda fazla mesai ücreti görünmemekte, tanık beyanları işçiyi doğrulamaktadır.",
    ruling: "Fazla mesai ücretinin ödenmesine karar verilmiştir. Tanık beyanları ve işyeri giriş-çıkış kayıtları belirleyici olmuştur.",
    keywords: ["fazla mesai", "çalışma saatleri", "bordro", "tanık beyanı", "ücret alacağı"],
    outcome: "plaintiff_won",
  },
  // AİLE HUKUKU
  {
    court: "Yargıtay 2. Hukuk Dairesi",
    case_number: "2023/3456 E., 2023/7890 K.",
    date: "2023-05-10",
    category: "aile_hukuku",
    summary: "Anlaşmalı boşanma sonrası nafaka artırım talebi. Davacı, ekonomik koşulların değiştiğini ve çocuğun okul masraflarının arttığını ileri sürmüştür.",
    ruling: "Nafakanın ÜFE oranında artırılmasına karar verilmiştir. Çocuğun eğitim masrafları dikkate alınmıştır.",
    keywords: ["nafaka artırımı", "boşanma", "çocuk nafakası", "eğitim masrafları", "ÜFE"],
    outcome: "plaintiff_won",
  },
  {
    court: "Yargıtay 2. Hukuk Dairesi",
    case_number: "2023/2211 E., 2023/4455 K.",
    date: "2023-04-22",
    category: "aile_hukuku",
    summary: "Velayet davası - Annenin velayeti talep etmesi. Baba, çocuğu okuldan almamakta ve ilgilenmemektedir. Sosyal inceleme raporu anneyi desteklemektedir.",
    ruling: "Velayetin anneye verilmesine, baba ile kişisel ilişki tesisine karar verilmiştir.",
    keywords: ["velayet", "çocuk hakları", "sosyal inceleme", "kişisel ilişki", "anne hakkı"],
    outcome: "plaintiff_won",
  },
  // TÜKETİCİ HUKUKU
  {
    court: "Yargıtay 3. Hukuk Dairesi",
    case_number: "2023/6789 E., 2023/9012 K.",
    date: "2023-06-05",
    category: "tuketici_hukuku",
    summary: "Ayıplı mal satışı - Araçta gizli ayıp tespit edilmesi. Satın alınan sıfır araçta 6 ay içinde motor arızası çıkmış, serviste üretim hatası tespit edilmiştir.",
    ruling: "Aracın iadesine ve satış bedelinin tüketiciye geri ödenmesine karar verilmiştir.",
    keywords: ["ayıplı mal", "araç", "üretim hatası", "tüketici hakları", "iade"],
    outcome: "plaintiff_won",
  },
  {
    court: "Tüketici Hakem Heyeti",
    case_number: "2023/THH-4521",
    date: "2023-07-12",
    category: "tuketici_hukuku",
    summary: "Online alışverişte cayma hakkı kullanımı. Tüketici 14 gün içinde cayma hakkını kullanmış ancak satıcı iade bedelini ödememiştir.",
    ruling: "Satıcının iade bedelini 14 gün içinde ödemesine karar verilmiştir.",
    keywords: ["cayma hakkı", "online alışveriş", "iade", "e-ticaret", "tüketici"],
    outcome: "plaintiff_won",
  },
  // KİRA HUKUKU
  {
    court: "Yargıtay 3. Hukuk Dairesi",
    case_number: "2022/11234 E., 2023/3344 K.",
    date: "2023-03-28",
    category: "kira_hukuku",
    summary: "Kira bedelinin tespiti davası. Kiracı 5 yıldır aynı dairede oturmakta, kira bedeli emsal kiraların çok altında kalmıştır.",
    ruling: "Kira bedelinin bilirkişi raporuna göre emsal kiralara uygun şekilde artırılmasına karar verilmiştir.",
    keywords: ["kira tespit", "emsal kira", "bilirkişi", "kira artışı", "kiracı"],
    outcome: "plaintiff_won",
  },
  {
    court: "Yargıtay 6. Hukuk Dairesi",
    case_number: "2023/7788 E., 2023/9900 K.",
    date: "2023-08-15",
    category: "kira_hukuku",
    summary: "Tahliye davası - Kiracının kira borcunu ödememesi. Kiracı 2 ay üst üste kira ödememiş, ihtar çekilmesine rağmen borç ödenmemiştir.",
    ruling: "Kiracının tahliyesine ve birikmiş kira bedellerinin tahsiline karar verilmiştir.",
    keywords: ["tahliye", "kira borcu", "ihtar", "icra", "kiracı tahliyesi"],
    outcome: "plaintiff_won",
  },
  // CEZA HUKUKU
  {
    court: "Yargıtay 4. Ceza Dairesi",
    case_number: "2023/4455 E., 2023/6677 K.",
    date: "2023-09-01",
    category: "ceza_hukuku",
    summary: "Hakaret suçu - Sosyal medya üzerinden hakaret. Sanık, mağdura sosyal medyada alenen hakaret içerikli paylaşımlar yapmıştır.",
    ruling: "Sanığın TCK 125/1 uyarınca adli para cezasına çarptırılmasına karar verilmiştir.",
    keywords: ["hakaret", "sosyal medya", "aleniyet", "adli para cezası", "TCK 125"],
    outcome: "plaintiff_won",
  },
  {
    court: "Yargıtay 15. Ceza Dairesi",
    case_number: "2022/9988 E., 2023/1100 K.",
    date: "2023-02-28",
    category: "ceza_hukuku",
    summary: "Dolandırıcılık suçu - İnternet üzerinden dolandırıcılık. Sanık, sahte ilan ile mağdurdan para almış ve ürünü göndermemiştir.",
    ruling: "Sanığın nitelikli dolandırıcılıktan mahkumiyetine ve mağdurun zararının tazmin edilmesine karar verilmiştir.",
    keywords: ["dolandırıcılık", "internet", "sahte ilan", "nitelikli dolandırıcılık", "tazminat"],
    outcome: "plaintiff_won",
  },
  // TİCARET HUKUKU
  {
    court: "Yargıtay 11. Hukuk Dairesi",
    case_number: "2023/5566 E., 2023/8899 K.",
    date: "2023-07-20",
    category: "ticaret_hukuku",
    summary: "Haksız rekabet davası - Rakip firmanın müşteri listesini kullanması. Eski çalışan, gizli müşteri bilgilerini rakip firmaya vermiştir.",
    ruling: "Haksız rekabetin tespitine, men'ine ve tazminata karar verilmiştir.",
    keywords: ["haksız rekabet", "ticari sır", "müşteri listesi", "tazminat", "rekabet yasağı"],
    outcome: "plaintiff_won",
  },
  // MİRAS HUKUKU
  {
    court: "Yargıtay 14. Hukuk Dairesi",
    case_number: "2023/3344 E., 2023/5566 K.",
    date: "2023-06-18",
    category: "miras_hukuku",
    summary: "Tenkis davası - Saklı pay ihlali. Miras bırakan, vasiyetname ile tüm malvarlığını tek bir çocuğuna bırakmış, diğer çocukların saklı paylarını ihlal etmiştir.",
    ruling: "Saklı pay oranında tenkise karar verilmiştir.",
    keywords: ["tenkis", "saklı pay", "vasiyetname", "miras", "mirasçı hakları"],
    outcome: "plaintiff_won",
  },
  // İDARE HUKUKU
  {
    court: "Danıştay 2. Dairesi",
    case_number: "2023/2233 E., 2023/4466 K.",
    date: "2023-05-30",
    category: "idare_hukuku",
    summary: "İdari işlemin iptali - Memura haksız disiplin cezası verilmesi. Memurun savunması alınmadan disiplin cezası uygulanmıştır.",
    ruling: "Savunma hakkı ihlali nedeniyle idari işlemin iptaline karar verilmiştir.",
    keywords: ["idari işlem", "iptal davası", "disiplin cezası", "savunma hakkı", "memur"],
    outcome: "plaintiff_won",
  },
  // İCRA İFLAS
  {
    court: "Yargıtay 12. Hukuk Dairesi",
    case_number: "2023/8877 E., 2023/1122 K.",
    date: "2023-04-10",
    category: "icra_iflas",
    summary: "İtirazın iptali davası - Borçlunun itirazının haksız bulunması. Alacaklı, senet ve fatura ile alacağını ispatlamıştır.",
    ruling: "İtirazın iptaline, %20 icra inkar tazminatına karar verilmiştir.",
    keywords: ["itirazın iptali", "icra", "senet", "alacak", "icra inkar tazminatı"],
    outcome: "plaintiff_won",
  },
  // Davalı kazanan örnekler
  {
    court: "Yargıtay 9. Hukuk Dairesi",
    case_number: "2023/7766 E., 2023/9988 K.",
    date: "2023-08-20",
    category: "is_hukuku",
    summary: "İşe iade davası - İşçinin devamsızlık yapması. İşçi, mazeretsiz ve üst üste 3 iş günü devamsızlık yapmıştır. İşveren tutanak tutmuştur.",
    ruling: "İşverenin haklı fesih yaptığına, işe iade talebinin reddine karar verilmiştir.",
    keywords: ["devamsızlık", "haklı fesih", "işveren hakkı", "tutanak", "işe iade reddi"],
    outcome: "defendant_won",
  },
  {
    court: "Yargıtay 2. Hukuk Dairesi",
    case_number: "2023/1133 E., 2023/3355 K.",
    date: "2023-09-15",
    category: "aile_hukuku",
    summary: "Nafaka davası - Yoksulluk nafakası talebinin reddi. Davacı tam zamanlı çalışmakta olup yeterli gelire sahiptir.",
    ruling: "Davacının yoksulluk nafakası talebinin reddine karar verilmiştir. Davacının çalışma gücü ve geliri yeterli bulunmuştur.",
    keywords: ["yoksulluk nafakası", "nafaka reddi", "gelir durumu", "çalışma gücü"],
    outcome: "defendant_won",
  },
  {
    court: "Yargıtay 3. Hukuk Dairesi",
    case_number: "2023/5544 E., 2023/7766 K.",
    date: "2023-10-05",
    category: "tuketici_hukuku",
    summary: "Ayıplı mal iddiasının reddi. Tüketici, ürünü kullanım kılavuzuna aykırı şekilde kullanmış ve oluşan hasar garanti kapsamı dışında kalmıştır.",
    ruling: "Ayıplı mal iddiasının reddine karar verilmiştir. Hasar kullanıcı hatasından kaynaklanmaktadır.",
    keywords: ["ayıplı mal reddi", "kullanıcı hatası", "garanti", "tüketici", "bilirkişi"],
    outcome: "defendant_won",
  },
];
